service: teamid-testing
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
custom: 
  defaultStage: experiments
  profiles:
    experiments: teamid-experiment # To be removed . For experiments only
    development: teamid-dev # change to Development AWS Profile
    production: teamid-prod # change to Production AWS Profile
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
